name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Clean Environment
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Clear iOS Pods
        run: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        run: flutter build ipa --no-codesign